/** Maharashtra & Konkan railway schedules — includes Kolhapur and major stations */

const mhImage = 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=500';

const makeSeats = (total) => ({
  '1A': Math.max(4, Math.floor(total * 0.08)),
  '2A': Math.max(8, Math.floor(total * 0.18)),
  '3A': Math.max(12, Math.floor(total * 0.28)),
  SL: Math.max(20, Math.floor(total * 0.46)),
});

const makeFare = (base) => ({
  '1A': base * 3.2,
  '2A': base * 2.1,
  '3A': base * 1.4,
  SL: base,
});

const daily = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

export const maharashtraTrains = [
  {
    trainNumber: '11029',
    trainName: 'Koyna Express',
    source: 'Kolhapur (KOP)',
    destination: 'Mumbai CSMT (CSMT)',
    departureTime: '08:10',
    arrivalTime: '20:45',
    duration: '12h 35m',
    totalSeats: 140,
    availableSeats: makeSeats(140),
    trainType: 'Express',
    fare: makeFare(420),
    runningDays: daily,
    image: mhImage,
    ratings: 4.5,
    stations: [
      { stationName: 'Kolhapur (KOP)', arrivalTime: '08:10', departureTime: '08:10', stopTime: 'Source', distance: 0 },
      { stationName: 'Miraj Junction (MRJ)', arrivalTime: '09:25', departureTime: '09:30', stopTime: '5 mins', distance: 52 },
      { stationName: 'Sangli (SLI)', arrivalTime: '09:55', departureTime: '10:00', stopTime: '5 mins', distance: 80 },
      { stationName: 'Karad (KRD)', arrivalTime: '10:45', departureTime: '10:48', stopTime: '3 mins', distance: 130 },
      { stationName: 'Satara (STR)', arrivalTime: '11:35', departureTime: '11:38', stopTime: '3 mins', distance: 185 },
      { stationName: 'Pune Junction (PUNE)', arrivalTime: '13:20', departureTime: '13:35', stopTime: '15 mins', distance: 288 },
      { stationName: 'Lonavala (LNL)', arrivalTime: '15:10', departureTime: '15:12', stopTime: '2 mins', distance: 356 },
      { stationName: 'Kalyan Junction (KYN)', arrivalTime: '18:40', departureTime: '18:45', stopTime: '5 mins', distance: 468 },
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '20:45', departureTime: '20:45', stopTime: 'Destination', distance: 518 },
    ],
  },
  {
    trainNumber: '11097',
    trainName: 'Pune Kolhapur DEMU',
    source: 'Pune Junction (PUNE)',
    destination: 'Kolhapur (KOP)',
    departureTime: '14:30',
    arrivalTime: '20:15',
    duration: '5h 45m',
    totalSeats: 100,
    availableSeats: makeSeats(100),
    trainType: 'Express',
    fare: makeFare(180),
    runningDays: daily,
    image: mhImage,
    ratings: 4.1,
    stations: [
      { stationName: 'Pune Junction (PUNE)', arrivalTime: '14:30', departureTime: '14:30', stopTime: 'Source', distance: 0 },
      { stationName: 'Satara (STR)', arrivalTime: '15:45', departureTime: '15:48', stopTime: '3 mins', distance: 103 },
      { stationName: 'Karad (KRD)', arrivalTime: '16:35', departureTime: '16:38', stopTime: '3 mins', distance: 158 },
      { stationName: 'Sangli (SLI)', arrivalTime: '17:25', departureTime: '17:28', stopTime: '3 mins', distance: 208 },
      { stationName: 'Miraj Junction (MRJ)', arrivalTime: '17:55', departureTime: '18:00', stopTime: '5 mins', distance: 236 },
      { stationName: 'Kolhapur (KOP)', arrivalTime: '20:15', departureTime: '20:15', stopTime: 'Destination', distance: 288 },
    ],
  },
  {
    trainNumber: '12148',
    trainName: 'Kolhapur Pune Superfast',
    source: 'Kolhapur (KOP)',
    destination: 'Pune Junction (PUNE)',
    departureTime: '06:00',
    arrivalTime: '11:20',
    duration: '5h 20m',
    totalSeats: 120,
    availableSeats: makeSeats(120),
    trainType: 'Superfast',
    fare: makeFare(220),
    runningDays: daily,
    image: mhImage,
    ratings: 4.4,
    stations: [
      { stationName: 'Kolhapur (KOP)', arrivalTime: '06:00', departureTime: '06:00', stopTime: 'Source', distance: 0 },
      { stationName: 'Miraj Junction (MRJ)', arrivalTime: '07:05', departureTime: '07:08', stopTime: '3 mins', distance: 52 },
      { stationName: 'Sangli (SLI)', arrivalTime: '07:35', departureTime: '07:38', stopTime: '3 mins', distance: 80 },
      { stationName: 'Karad (KRD)', arrivalTime: '08:25', departureTime: '08:28', stopTime: '3 mins', distance: 130 },
      { stationName: 'Satara (STR)', arrivalTime: '09:15', departureTime: '09:18', stopTime: '3 mins', distance: 185 },
      { stationName: 'Pune Junction (PUNE)', arrivalTime: '11:20', departureTime: '11:20', stopTime: 'Destination', distance: 288 },
    ],
  },
  {
    trainNumber: '11011',
    trainName: 'Mumbai Kolhapur Mahalaxmi Express',
    source: 'Mumbai CSMT (CSMT)',
    destination: 'Kolhapur (KOP)',
    departureTime: '20:20',
    arrivalTime: '07:30',
    duration: '11h 10m',
    totalSeats: 160,
    availableSeats: makeSeats(160),
    trainType: 'Express',
    fare: makeFare(450),
    runningDays: daily,
    image: mhImage,
    ratings: 4.6,
    stations: [
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '20:20', departureTime: '20:20', stopTime: 'Source', distance: 0 },
      { stationName: 'Pune Junction (PUNE)', arrivalTime: '23:55', departureTime: '00:10', stopTime: '15 mins', distance: 230 },
      { stationName: 'Satara (STR)', arrivalTime: '02:05', departureTime: '02:08', stopTime: '3 mins', distance: 333 },
      { stationName: 'Sangli (SLI)', arrivalTime: '03:40', departureTime: '03:43', stopTime: '3 mins', distance: 438 },
      { stationName: 'Miraj Junction (MRJ)', arrivalTime: '04:10', departureTime: '04:15', stopTime: '5 mins', distance: 466 },
      { stationName: 'Kolhapur (KOP)', arrivalTime: '07:30', departureTime: '07:30', stopTime: 'Destination', distance: 518 },
    ],
  },
  {
    trainNumber: '12123',
    trainName: 'Mumbai Pune Deccan Queen',
    source: 'Mumbai CSMT (CSMT)',
    destination: 'Pune Junction (PUNE)',
    departureTime: '07:15',
    arrivalTime: '10:35',
    duration: '3h 20m',
    totalSeats: 110,
    availableSeats: makeSeats(110),
    trainType: 'Shatabdi',
    fare: makeFare(320),
    runningDays: daily,
    image: mhImage,
    ratings: 4.7,
    stations: [
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '07:15', departureTime: '07:15', stopTime: 'Source', distance: 0 },
      { stationName: 'Lonavala (LNL)', arrivalTime: '08:55', departureTime: '08:57', stopTime: '2 mins', distance: 112 },
      { stationName: 'Pune Junction (PUNE)', arrivalTime: '10:35', departureTime: '10:35', stopTime: 'Destination', distance: 192 },
    ],
  },
  {
    trainNumber: '12105',
    trainName: 'Vidarbha Express',
    source: 'Mumbai CSMT (CSMT)',
    destination: 'Nagpur Junction (NGP)',
    departureTime: '19:10',
    arrivalTime: '09:15',
    duration: '14h 05m',
    totalSeats: 150,
    availableSeats: makeSeats(150),
    trainType: 'Superfast',
    fare: makeFare(520),
    runningDays: daily,
    image: mhImage,
    ratings: 4.5,
    stations: [
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '19:10', departureTime: '19:10', stopTime: 'Source', distance: 0 },
      { stationName: 'Nasik Road (NK)', arrivalTime: '22:40', departureTime: '22:45', stopTime: '5 mins', distance: 180 },
      { stationName: 'Bhusaval Junction (BSL)', arrivalTime: '02:30', departureTime: '02:40', stopTime: '10 mins', distance: 445 },
      { stationName: 'Nagpur Junction (NGP)', arrivalTime: '09:15', departureTime: '09:15', stopTime: 'Destination', distance: 837 },
    ],
  },
  {
    trainNumber: '11013',
    trainName: 'Mumbai Aurangabad Express',
    source: 'Mumbai CSMT (CSMT)',
    destination: 'Chhatrapati Sambhajinagar (AUR)',
    departureTime: '22:45',
    arrivalTime: '07:20',
    duration: '8h 35m',
    totalSeats: 130,
    availableSeats: makeSeats(130),
    trainType: 'Express',
    fare: makeFare(380),
    runningDays: daily,
    image: mhImage,
    ratings: 4.3,
    stations: [
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '22:45', departureTime: '22:45', stopTime: 'Source', distance: 0 },
      { stationName: 'Manmad Junction (MMR)', arrivalTime: '03:10', departureTime: '03:20', stopTime: '10 mins', distance: 260 },
      { stationName: 'Chhatrapati Sambhajinagar (AUR)', arrivalTime: '07:20', departureTime: '07:20', stopTime: 'Destination', distance: 375 },
    ],
  },
  {
    trainNumber: '11003',
    trainName: 'Rajya Rani Express Ratnagiri',
    source: 'Mumbai CSMT (CSMT)',
    destination: 'Ratnagiri (RN)',
    departureTime: '15:50',
    arrivalTime: '22:40',
    duration: '6h 50m',
    totalSeats: 100,
    availableSeats: makeSeats(100),
    trainType: 'Express',
    fare: makeFare(290),
    runningDays: daily,
    image: mhImage,
    ratings: 4.2,
    stations: [
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '15:50', departureTime: '15:50', stopTime: 'Source', distance: 0 },
      { stationName: 'Panvel (PNVL)', arrivalTime: '16:35', departureTime: '16:37', stopTime: '2 mins', distance: 48 },
      { stationName: 'Khed (KHED)', arrivalTime: '19:20', departureTime: '19:22', stopTime: '2 mins', distance: 198 },
      { stationName: 'Ratnagiri (RN)', arrivalTime: '22:40', departureTime: '22:40', stopTime: 'Destination', distance: 352 },
    ],
  },
  {
    trainNumber: '11301',
    trainName: 'Solapur Kolhapur Express',
    source: 'Solapur (SUR)',
    destination: 'Kolhapur (KOP)',
    departureTime: '05:30',
    arrivalTime: '10:45',
    duration: '5h 15m',
    totalSeats: 90,
    availableSeats: makeSeats(90),
    trainType: 'Express',
    fare: makeFare(200),
    runningDays: ['Mon', 'Wed', 'Fri', 'Sun'],
    image: mhImage,
    ratings: 4.0,
    stations: [
      { stationName: 'Solapur (SUR)', arrivalTime: '05:30', departureTime: '05:30', stopTime: 'Source', distance: 0 },
      { stationName: 'Miraj Junction (MRJ)', arrivalTime: '08:50', departureTime: '08:55', stopTime: '5 mins', distance: 178 },
      { stationName: 'Kolhapur (KOP)', arrivalTime: '10:45', departureTime: '10:45', stopTime: 'Destination', distance: 230 },
    ],
  },
  {
    trainNumber: '11035',
    trainName: 'Goa Express via Kolhapur',
    source: 'Kolhapur (KOP)',
    destination: 'Madgaon (MAO)',
    departureTime: '12:00',
    arrivalTime: '21:30',
    duration: '9h 30m',
    totalSeats: 120,
    availableSeats: makeSeats(120),
    trainType: 'Express',
    fare: makeFare(350),
    runningDays: daily,
    image: mhImage,
    ratings: 4.4,
    stations: [
      { stationName: 'Kolhapur (KOP)', arrivalTime: '12:00', departureTime: '12:00', stopTime: 'Source', distance: 0 },
      { stationName: 'Miraj Junction (MRJ)', arrivalTime: '13:05', departureTime: '13:10', stopTime: '5 mins', distance: 52 },
      { stationName: 'Belagavi (BGM)', arrivalTime: '15:20', departureTime: '15:25', stopTime: '5 mins', distance: 145 },
      { stationName: 'Madgaon (MAO)', arrivalTime: '21:30', departureTime: '21:30', stopTime: 'Destination', distance: 310 },
    ],
  },
  {
    trainNumber: '11049',
    trainName: 'Kolhapur Mumbai Vande Bharat',
    source: 'Kolhapur (KOP)',
    destination: 'Mumbai CSMT (CSMT)',
    departureTime: '06:30',
    arrivalTime: '12:45',
    duration: '6h 15m',
    totalSeats: 80,
    availableSeats: makeSeats(80),
    trainType: 'Vande Bharat',
    fare: makeFare(680),
    runningDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    image: mhImage,
    ratings: 4.9,
    stations: [
      { stationName: 'Kolhapur (KOP)', arrivalTime: '06:30', departureTime: '06:30', stopTime: 'Source', distance: 0 },
      { stationName: 'Sangli (SLI)', arrivalTime: '07:20', departureTime: '07:22', stopTime: '2 mins', distance: 80 },
      { stationName: 'Pune Junction (PUNE)', arrivalTime: '09:00', departureTime: '09:05', stopTime: '5 mins', distance: 288 },
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '12:45', departureTime: '12:45', stopTime: 'Destination', distance: 518 },
    ],
  },
  {
    trainNumber: '11051',
    trainName: 'Nashik Mumbai Passenger',
    source: 'Nasik Road (NK)',
    destination: 'Mumbai CSMT (CSMT)',
    departureTime: '09:00',
    arrivalTime: '13:15',
    duration: '4h 15m',
    totalSeats: 100,
    availableSeats: makeSeats(100),
    trainType: 'Express',
    fare: makeFare(150),
    runningDays: daily,
    image: mhImage,
    ratings: 3.9,
    stations: [
      { stationName: 'Nasik Road (NK)', arrivalTime: '09:00', departureTime: '09:00', stopTime: 'Source', distance: 0 },
      { stationName: 'Kalyan Junction (KYN)', arrivalTime: '12:20', departureTime: '12:22', stopTime: '2 mins', distance: 128 },
      { stationName: 'Mumbai CSMT (CSMT)', arrivalTime: '13:15', departureTime: '13:15', stopTime: 'Destination', distance: 180 },
    ],
  },
];

export const MH_STATIONS = [
  'Kolhapur (KOP)',
  'Mumbai CSMT (CSMT)',
  'Pune Junction (PUNE)',
  'Miraj Junction (MRJ)',
  'Sangli (SLI)',
  'Solapur (SUR)',
  'Nagpur Junction (NGP)',
  'Nasik Road (NK)',
  'Ratnagiri (RN)',
  'Chhatrapati Sambhajinagar (AUR)',
  'Satara (STR)',
  'Karad (KRD)',
  'Kalyan Junction (KYN)',
  'Lonavala (LNL)',
  'Belagavi (BGM)',
  'Madgaon (MAO)',
];
